### ISSUE TITLE
purchase_usability action filters from account.invoice

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/purchase#24]
Los filtros que se aplican por defecto en la acción definida en `account.invoice` no están funcionando bien.

Por un lado, intenta aplicar el filtro `to invoice` que fue eliminado en https://github.com/ingadhoc/purchase/commit/b3872cf4ea7f40f1bf4d5adf93f51aefad781f42#diff-6adefe8989db75ada43390076f533b35R63

Por otro lado, se aplica por defecto el filtro "En factura actual" que, salvo que yo me esté perdiendo de algo, en el uso común y corriente es impráctico ya que a la hora de apretar el botón "Agregar lineas de compra" la factura no tienen ninguna línea.. por lo tanto, el resultado de ese filtro es 0 registros.

Creo yo que, en realidad, se deberían aplicar los filtros "No facturado" y "A facturar" (un filtro nuevo) `[('qty_to_invoice', '>', 0)]`

O bien corregir el `qty_to_invoice` para que ignore las OC con `manually_set_invoiced`, y así aplicar únicamente este último filtro.

**Comment by jjscarafia** [comment]
Buenas Ivan,
El filtro "No facturado" en realidad es "A Facturar", lo dejamos con ese label porque es el label que trae odoo por defecto (se puede ver [acá](https://github.com/odoo/odoo/blob/9.0/addons/purchase/purchase_view.xml#L296)). Vamos a analizar pisar ese label para la v11.

Por esa razón es que borramos el "A facturar", porque ya lo cubre el actual "No facturado".

Respecto al filtro "En factura actual", ese está porque esta funcionalidad de ir a las líneas surgió como extensión al uso nativo de odoo de generar una factura de compra desde la orden de compra (y en ese caso agrega todas las líneas). Como es un cambio de funcionalidad que afecta a clientes que ya están en producción, también lo vamos a analizar para ver si es mejor sacar ese valor por defecto directamente en v11.
