### ISSUE TITLE
[8.0] purchase_add_products_wizard and sales_add_products_wizard extend feature

### ISSUE THREAD

**Issue by bunhin** [ingadhoc/purchase#6]
add feature expected, add option for quantity generation to be based on unit pack composition and the total order needed

unit-pack-composition defined as all variants of a product template that is packed in certain quantity and each variants in the pack may have different quantity.  For example a model of t-shirt (a template) have size as a attribute and have 6 size attributes value: xs  s  m  l  xl  and xxl  pack in a unit pack named "12PCSMIXSIZE" that consist of  
1 unit size xs, 
2 unit size s
3 unit size m
3 unit size l
2 unit size xl
1 unit size xxl

to generate order lines   select product template (single or multiple), input total quantity for a template and select the unit-pack,

**Comment by jjscarafia** [comment]
Sorry but I don't understand the issue or suggestion. 
Do you suggest to integrate this modules "sales_add_products_wizard" and "purchase_add_products_wizard" with another one or a native odoo functionality?

This 2 modules, sales_add_products_wizard and purchase_add_products_wizard has been depreceated and replaced by "purchase_quotation_products" and "sale_quotation_products", you can check them

**Comment by bunhin** [comment]
Dear jjscarafia,
Thanks for response, i am sorry for delayed response back.
Actually i recommend to add feature for the wizard to speedup process of creating order lines by automatic generate variable order quantity especially when we are working with product variants for fashion industries. In existing wizard of your modules (sales_add_products_wizard and purchase_add_products_wizard) the order qty is already automatically generated for each order lines based on input qty, but all lines have the same quantity.

please let me explain in more detail as below:
In fashion industries mostly using variants (size or color) as attribute and when purchase or sell fashion products mostly use a certain unit pack as composition of the variants which has variations in quantity of each variant in the unit pack.

Said a model of T-shirt  has size attribute with 6 values for example:
Size XS
Size S
Size M
Size L
Size XL
Size XXL

The T-shirt is purchased or sold with  a unit pack of 12 pcs where this 12 pcs unit pack is composed from the t-shirt variant in size.
unit pack composition:
Size XS = 1 pc
Size S   = 2 pcs
Size M  = 3 pcs
Size L   = 3 pcs
Size XL = 2 pcs
Size XXL = 1 pcs
total unit pack = 12 pcs composed from all 6 variants

Expected new feature of your wizard:
1. we can choose whether the order lines will have same order qty for all order lines or will have variable quantity based on total order and a certain composition
2. if same order quantity is chosen, the wizard will do as existing now, or
   if variable in quantity chosen: 
3. the wizard will ask user to select a product template and select the unit pack composition, and the total quantity of order for the template
4. base on the input/selection the wizard will generate order lines which quantity of each order line automatically calculated. for example with above example unit pack composition is chosen and 1500 pcs total order input, the order qty for size xs will be 125 pcs,  for size s = 250 pcs, for size m = 375 pcs for size l = 375 pcs, for size xl =250 pcs and for size xxl = 125 pcs.

I hope to be clear enough, and the module can have above extra feature.

Thank you

**Comment by jjscarafia** [comment]
I understant more now. But we have depreceate this two modules and no more wizard is there. Of course you can fork and mantain this two modules (with your modifications also).
We've replace this functionality with purchase_quotation_products" and "sale_quotation_products but I think they won't solve your need neither
